  {
    id: 'noche-de-rabanos',
    title: 'Noche de Rábanos (Night of Radishes)',
    coordinates: [17.076, -96.726],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-12-23',
    endDate: '2026-12-23',
    verified: true,
    region: 'Oaxaca, Mexico',
    description: 'Noche de Rábanos (Night of Radishes), a renowned cultural phenomenon celebrated in Oaxaca, Mexico. This traditionally takes place around December 23.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/NocheRabanos1L.JPG/800px-NocheRabanos1L.JPG',
    mediaLinks: {}
  },
  {
    id: 'la-tamborrada',
    title: 'La Tamborrada (Drum Festival)',
    coordinates: [43.318, -1.981],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-01-20',
    endDate: '2026-01-20',
    verified: true,
    region: 'San Sebastián, Spain',
    description: 'La Tamborrada (Drum Festival), a renowned cultural phenomenon celebrated in San Sebastián, Spain. This traditionally takes place around January 20.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Tamborrada_San_Sebastian_2011.jpg/800px-Tamborrada_San_Sebastian_2011.jpg',
    mediaLinks: {}
  },
  {
    id: 'nieuwjaarsduik',
    title: 'Nieuwjaarsduik (New Year\'s Dive)',
    coordinates: [52.113, 4.281],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-01-01',
    endDate: '2026-01-01',
    verified: true,
    region: 'Netherlands (Scheveningen)',
    description: 'Nieuwjaarsduik (New Year\'s Dive), a renowned cultural phenomenon celebrated in Netherlands (Scheveningen). This traditionally takes place around January 1.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Nieuwjaarsduik_Scheveningen_2019.jpg/800px-Nieuwjaarsduik_Scheveningen_2019.jpg',
    mediaLinks: {}
  },
  {
    id: 'ngaben',
    title: 'Ngaben (Balinese Funeral Ritual)',
    coordinates: [-8.340, 115.092],
    ritualType: RitualType.CEREMONY,
    subCategory: 'Ritual',
    startDate: '2026-05-01',
    endDate: '2026-05-01',
    verified: true,
    region: 'Bali, Indonesia',
    description: 'Ngaben (Balinese Funeral Ritual), a renowned cultural phenomenon celebrated in Bali, Indonesia. This traditionally takes place around Varies (check local calendar).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Pelebon_Agung.jpg/800px-Pelebon_Agung.jpg',
    mediaLinks: {}
  },
  {
    id: 'up-helly-aa',
    title: 'Up Helly Aa (Viking Fire Festival)',
    coordinates: [60.155, -1.145],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Fire',
    startDate: '2026-01-27',
    endDate: '2026-01-27',
    verified: true,
    region: 'Lerwick, Shetland',
    description: 'Up Helly Aa (Viking Fire Festival), a renowned cultural phenomenon celebrated in Lerwick, Shetland. This traditionally takes place around Last Tuesday of January.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Up_Helly_Aa_%2816301325492%29.jpg/800px-Up_Helly_Aa_%2816301325492%29.jpg',
    mediaLinks: {}
  },
  {
    id: 'tinku',
    title: 'Tinku (Ritual Fighting)',
    coordinates: [-19.589, -65.753],
    ritualType: RitualType.CEREMONY,
    subCategory: 'Ritual',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    verified: true,
    region: 'Potosí region, Bolivia',
    description: 'Tinku (Ritual Fighting), a renowned cultural phenomenon celebrated in Potosí region, Bolivia. This traditionally takes place around May (specifically early May).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Tinku_Macha_Bolivia.jpg/800px-Tinku_Macha_Bolivia.jpg',
    mediaLinks: {}
  },
  {
    id: 'feria-de-sevilla',
    title: 'Feria de Sevilla',
    coordinates: [37.389, -5.984],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-04-20',
    endDate: '2026-04-20',
    verified: true,
    region: 'Seville, Spain',
    description: 'Feria de Sevilla, a renowned cultural phenomenon celebrated in Seville, Spain. This traditionally takes place around Two weeks after Easter.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Feria_de_Abril_de_Sevilla_%282006%29.jpg/800px-Feria_de_Abril_de_Sevilla_%282006%29.jpg',
    mediaLinks: {}
  },
  {
    id: 'banho-29',
    title: 'Banho 29 (Traditional Midnight Swim)',
    coordinates: [37.102, -8.673],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Water',
    startDate: '2026-08-29',
    endDate: '2026-08-29',
    verified: true,
    region: 'Lagos, Portugal',
    description: 'Banho 29 (Traditional Midnight Swim), a renowned cultural phenomenon celebrated in Lagos, Portugal. This traditionally takes place around August 29.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Praia_da_Batata_Lagos.jpg/800px-Praia_da_Batata_Lagos.jpg',
    mediaLinks: {}
  },
  {
    id: 'wife-carrying-world-championship',
    title: 'Wife Carrying World Championship',
    coordinates: [63.669, 27.676],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-07-04',
    endDate: '2026-07-04',
    verified: true,
    region: 'Sonkajärvi, Finland',
    description: 'Wife Carrying World Championship, a renowned cultural phenomenon celebrated in Sonkajärvi, Finland. This traditionally takes place around July.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Wife_carrying_Sonkajarvi_2008_7.jpg/800px-Wife_carrying_Sonkajarvi_2008_7.jpg',
    mediaLinks: {}
  },
  {
    id: 'kite-festival',
    title: 'Kite Festival (Giant Barriletes)',
    coordinates: [14.646, -90.733],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-11-01',
    endDate: '2026-11-01',
    verified: true,
    region: 'Sumpango, Guatemala',
    description: 'Kite Festival (Giant Barriletes), a renowned cultural phenomenon celebrated in Sumpango, Guatemala. This traditionally takes place around November 1.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Festival_de_Barriletes_Gigantes%2C_Sumpango_2016-18.jpg/800px-Festival_de_Barriletes_Gigantes%2C_Sumpango_2016-18.jpg',
    mediaLinks: {}
  },
  {
    id: 'tapati-rapa-nui',
    title: 'Tapati Rapa Nui',
    coordinates: [-27.112, -109.349],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-02-05',
    endDate: '2026-02-05',
    verified: true,
    region: 'Easter Island, Chile',
    description: 'Tapati Rapa Nui, a renowned cultural phenomenon celebrated in Easter Island, Chile. This traditionally takes place around First two weeks of February.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Rapa_Nui_-_Tapati_festival.jpg/800px-Rapa_Nui_-_Tapati_festival.jpg',
    mediaLinks: {}
  },
  {
    id: 'naha-great-tug-of-war',
    title: 'Naha Great Tug of War',
    coordinates: [26.212, 127.679],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-10-10',
    endDate: '2026-10-10',
    verified: true,
    region: 'Okinawa, Japan',
    description: 'Naha Great Tug of War, a renowned cultural phenomenon celebrated in Okinawa, Japan. This traditionally takes place around October (Health & Sports Day).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Naha_tug_of_war_2010.jpg/800px-Naha_tug_of_war_2010.jpg',
    mediaLinks: {}
  },
  {
    id: 'il-palio',
    title: 'Il Palio (Horse Race)',
    coordinates: [43.318, 11.330],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-07-02',
    endDate: '2026-07-02',
    verified: true,
    region: 'Siena, Italy',
    description: 'Il Palio (Horse Race), a renowned cultural phenomenon celebrated in Siena, Italy. This traditionally takes place around July 2 and August 16.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Palio_2005.jpg/800px-Palio_2005.jpg',
    mediaLinks: {}
  },
  {
    id: 'lewes-bonfire-night',
    title: 'Lewes Bonfire Night',
    coordinates: [50.874, 0.012],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Fire',
    startDate: '2026-11-05',
    endDate: '2026-11-05',
    verified: true,
    region: 'Lewes, UK',
    description: 'Lewes Bonfire Night, a renowned cultural phenomenon celebrated in Lewes, UK. This traditionally takes place around November 5.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Lewes_Bonfire_Night_2011_-_Cliffe_Society_First_Procession.jpg/800px-Lewes_Bonfire_Night_2011_-_Cliffe_Society_First_Procession.jpg',
    mediaLinks: {}
  },
  {
    id: 'the-padstow-obby-oss',
    title: 'The Padstow \'Obby \'Oss',
    coordinates: [50.541, -4.939],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-05-01',
    endDate: '2026-05-01',
    verified: true,
    region: 'Padstow, Cornwall, UK',
    description: 'The Padstow \'Obby \'Oss, a renowned cultural phenomenon celebrated in Padstow, Cornwall, UK. This traditionally takes place around May 1 (May Day).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Padstow_Obby_Oss_-_Old_Oss.jpg/800px-Padstow_Obby_Oss_-_Old_Oss.jpg',
    mediaLinks: {}
  },
  {
    id: 'tiji-festival',
    title: 'Tiji Festival',
    coordinates: [29.182, 83.956],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-05-15',
    endDate: '2026-05-15',
    verified: true,
    region: 'Lo Manthang, Nepal',
    description: 'Tiji Festival, a renowned cultural phenomenon celebrated in Lo Manthang, Nepal. This traditionally takes place around May (Tibetan Lunar Calendar).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Tiji_Festival.jpg/800px-Tiji_Festival.jpg',
    mediaLinks: {}
  },
  {
    id: 'sapporo-snow-festival',
    title: 'Sapporo Snow Festival',
    coordinates: [43.062, 141.354],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-02-05',
    endDate: '2026-02-05',
    verified: true,
    region: 'Sapporo, Japan',
    description: 'Sapporo Snow Festival, a renowned cultural phenomenon celebrated in Sapporo, Japan. This traditionally takes place around Early February.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sapporo_Snow_Festival_2010.jpg/800px-Sapporo_Snow_Festival_2010.jpg',
    mediaLinks: {}
  },
  {
    id: 'grand-kadooment',
    title: 'Grand Kadooment (Crop Over)',
    coordinates: [13.193, -59.543],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-08-03',
    endDate: '2026-08-03',
    verified: true,
    region: 'Barbados',
    description: 'Grand Kadooment (Crop Over), a renowned cultural phenomenon celebrated in Barbados. This traditionally takes place around First Monday of August.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Crop_Over_Grand_Kadooment_2011.jpg/800px-Crop_Over_Grand_Kadooment_2011.jpg',
    mediaLinks: {}
  },
  {
    id: 'atherstone-ball-game',
    title: 'Atherstone Ball Game',
    coordinates: [52.577, -1.547],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-02-17',
    endDate: '2026-02-17',
    verified: true,
    region: 'Atherstone, UK',
    description: 'Atherstone Ball Game, a renowned cultural phenomenon celebrated in Atherstone, UK. This traditionally takes place around Shrove Tuesday (Feb/March).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Atherstone_Ball_Game_2011.jpg/800px-Atherstone_Ball_Game_2011.jpg',
    mediaLinks: {}
  },
  {
    id: 'international-worm-charming',
    title: 'International Worm Charming',
    coordinates: [53.078, -2.476],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-06-25',
    endDate: '2026-06-25',
    verified: true,
    region: 'Willaston, UK',
    description: 'International Worm Charming, a renowned cultural phenomenon celebrated in Willaston, UK. This traditionally takes place around June.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Worm_charming.jpg/800px-Worm_charming.jpg',
    mediaLinks: {}
  },
  {
    id: 'voodoo-festival',
    title: 'Voodoo Festival',
    coordinates: [6.363, 2.085],
    ritualType: RitualType.SPIRITUAL,
    subCategory: 'Magic',
    startDate: '2026-01-10',
    endDate: '2026-01-10',
    verified: true,
    region: 'Ouidah, Benin',
    description: 'Voodoo Festival, a renowned cultural phenomenon celebrated in Ouidah, Benin. This traditionally takes place around January 10.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Ouidah_Voodoo_Festival_2008.jpg/800px-Ouidah_Voodoo_Festival_2008.jpg',
    mediaLinks: {}
  },
  {
    id: 'la-paz-day-parade',
    title: 'La Paz Day Parade',
    coordinates: [-16.489, -68.119],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-07-16',
    endDate: '2026-07-16',
    verified: true,
    region: 'La Paz, Bolivia',
    description: 'La Paz Day Parade, a renowned cultural phenomenon celebrated in La Paz, Bolivia. This traditionally takes place around July 16.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/La_Paz_city_center.jpg/800px-La_Paz_city_center.jpg',
    mediaLinks: {}
  },
  {
    id: 'st-patricks-parade',
    title: 'St. Patrick\'s Parade',
    coordinates: [35.666, 139.706],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-03-17',
    endDate: '2026-03-17',
    verified: true,
    region: 'Tokyo, Japan',
    description: 'St. Patrick\'s Parade, a renowned cultural phenomenon celebrated in Tokyo, Japan. This traditionally takes place around March (around the 17th).',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/St._Patrick%27s_Day_parade_in_Tokyo.jpg/800px-St._Patrick%27s_Day_parade_in_Tokyo.jpg',
    mediaLinks: {}
  },
  {
    id: 'ted-fest',
    title: 'Ted Fest (Father Ted Tribute)',
    coordinates: [53.125, -9.722],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-02-20',
    endDate: '2026-02-20',
    verified: true,
    region: 'Inis Mór, Ireland',
    description: 'Ted Fest (Father Ted Tribute), a renowned cultural phenomenon celebrated in Inis Mór, Ireland. This traditionally takes place around Late February.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Inishmore_Pier.jpg/800px-Inishmore_Pier.jpg',
    mediaLinks: {}
  },
  {
    id: 'jazz-fest',
    title: 'Jazz Fest',
    coordinates: [29.981, -90.078],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Musical',
    startDate: '2026-04-24',
    endDate: '2026-04-24',
    verified: true,
    region: 'New Orleans, USA',
    description: 'Jazz Fest, a renowned cultural phenomenon celebrated in New Orleans, USA. This traditionally takes place around Late April / Early May.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Jazz_Fest_New_Orleans_2010.jpg/800px-Jazz_Fest_New_Orleans_2010.jpg',
    mediaLinks: {}
  },
  {
    id: 'red-dress-run',
    title: 'Red Dress Run',
    coordinates: [29.958, -90.064],
    ritualType: RitualType.FESTIVAL,
    subCategory: 'Cultural',
    startDate: '2026-08-08',
    endDate: '2026-08-08',
    verified: true,
    region: 'New Orleans, USA',
    description: 'Red Dress Run, a renowned cultural phenomenon celebrated in New Orleans, USA. This traditionally takes place around Second Saturday of August.',
    insights: 'Automated ingestion data batch from user request.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Red_Dress_Run_2011.jpg/800px-Red_Dress_Run_2011.jpg',
    mediaLinks: {}
  }
