
import React, { useState, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';
import { CultureItem } from '../types';
import { X, MapPin, BookOpen, ShoppingBag, Sparkles, Loader2, Calendar, AlignLeft, Backpack, Plane, ChevronRight, Sun, Images, Maximize2, Minimize2 } from 'lucide-react';
import { aiClient } from "../utils/aiClient";
import { categoryColor } from '../utils/categoryTheme';
import { cachedLocation, storeAiImage, storeLocation } from '../utils/aiImageCache';
import {
  EventBriefing,
  loadEventBriefings,
  meaningfulDescription
} from '../utils/eventBriefings';
import { useSwipeBack } from '../hooks/useSwipeBack';
import EventGallery from './EventGallery';
import GettingTherePanel from './GettingTherePanel';
import ConditionsPanel from './ConditionsPanel';
import {
  ClimateNormals,
  Daylight,
  fetchClimateNormals,
  fetchDaylight
} from '../utils/eventContext';

interface DetailPanelProps {
  item: CultureItem;
  onClose: () => void;
  isSaved?: boolean;
  onToggleSave?: () => void;
  /** Lets the flight handoff fill in a departure airport. */
  userCoords?: [number, number] | null;
  /** Opens the trip this event was just saved into. */
  onViewSaved?: () => void;
  /**
   * 'panel' is the 380px map column. 'reader' opens straight into the
   * full-window layout, for the desktop tabs that have no column to put a
   * panel in — the calendar, the library, the collections.
   */
  variant?: 'panel' | 'reader';
}


const DetailPanel: React.FC<DetailPanelProps> = ({ item, onClose, isSaved = false, onToggleSave, userCoords, onViewSaved, variant = 'panel' }) => {
  const [displayImage, setDisplayImage] = useState(item.imageUrl);
  const [isAiGenerated, setIsAiGenerated] = useState(false);
  const [isLoadingAi, setIsLoadingAi] = useState(false);
  const [preciseLocation, setPreciseLocation] = useState<string>('');
  const [activeTab, setActiveTab] = useState<'summary' | 'wikipedia'>('summary');
  const [wikiContent, setWikiContent] = useState<string | null>(null);
  const [isLoadingWiki, setIsLoadingWiki] = useState(false);
  const [briefing, setBriefing] = useState<EventBriefing | null>(null);
  // Desktop only: promote the 380px column to a full-screen reading layout.
  // A sidebar sets a measure of roughly 45 characters, which is half of what
  // continuous prose wants — the eye makes a return sweep every few words,
  // and that is what makes a long briefing tiring rather than the length.
  const [isReader, setIsReader] = useState(variant === 'reader');

  // Leaving the reader means going back to the column it grew out of, unless
  // there is no column — opened from the calendar or the library, the reader
  // *is* the panel, so closing it closes the event.
  const exitReader = () => (variant === 'reader' ? onClose() : setIsReader(false));

  // Sourced description, resolved once at build time rather than searched on
  // every open. Falls back to the catalogue line only when that line says
  // something the title and region do not already.
  useEffect(() => {
    let live = true;
    loadEventBriefings().then(all => {
      if (live) setBriefing(all[item.id] ?? null);
    });
    return () => { live = false; };
  }, [item.id]);

  useEffect(() => {
    if (!isReader) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') exitReader(); };
    window.addEventListener('keydown', onKey);
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = previous;
    };
  }, [isReader, variant, onClose]);

  const curatedNote = meaningfulDescription(item);

  // Extra verified frames arrive attached to the photograph the catalogue
  // already carries, so there is nothing more to fetch here.
  const gallery = item.imageCredit?.gallery ?? [];

  // Swiping right closes the panel, which on a phone is the gesture people
  // reach for before they look for the button in the far corner.
  const swipeBack = useSwipeBack(onClose);

  const [climate, setClimate] = useState<ClimateNormals | null>(null);
  const [daylight, setDaylight] = useState<Daylight | null>(null);

  useEffect(() => {
    let live = true;
    setClimate(null);
    setDaylight(null);

    const start = new Date(item.startDate);
    const end = new Date(item.endDate || item.startDate);
    if (Number.isNaN(start.getTime())) return;

    Promise.all([
      fetchClimateNormals(item.coordinates[0], item.coordinates[1], start, end),
      fetchDaylight(item.coordinates[0], item.coordinates[1], start)
    ]).then(([normals, sun]) => {
      if (!live) return;
      setClimate(normals);
      setDaylight(sun);
    }).catch(() => { /* a missing climate record is not an error worth showing */ });

    return () => { live = false; };
  }, [item.id]);

  // Track if we have already tried auto-generation for this item to prevent loops
  const hasAutoGeneratedRef = useRef<Set<string>>(new Set());
  const hasLocationFetchedRef = useRef<Set<string>>(new Set());

  /**
   * Place to show before the AI lookup returns, if it ever does.
   *
   * This used to capitalise whatever came before the first hyphen in the id
   * and present it as a country, which is only true when the id happens to
   * start with one. The Sardine Run is `phenom-the-sardine-run`, so the panel
   * announced its location as "Phenom"; the bulk-imported records gave
   * "Africa" and "Middle". The record already carries a real region, and it
   * is better than anything derivable from a slug.
   */
  const getInitialLocation = () => {
    const KNOWN_PREFIXES: Record<string, string> = {
      'nz': 'New Zealand',
      'uk': 'United Kingdom',
      'usa': 'United States',
      'png': 'Papua New Guinea',
      'cr': 'Costa Rica',
      'aus': 'Australia',
      'dr': 'Dominican Republic',
      'swiss': 'Switzerland'
    };
    if (item.region?.trim()) return item.region;
    const code = item.id?.split('-')[0] ?? '';
    return KNOWN_PREFIXES[code] ?? '';
  };

  useEffect(() => {
    // Reset states when item changes
    setActiveTab('summary');
    setWikiContent(null);
    setIsLoadingWiki(false);

    // --- IMAGE LOGIC ---
    setDisplayImage(item.imageUrl);
    setIsAiGenerated(false);
    setIsLoadingAi(false);

    // --- LOCATION LOGIC ---
    const cachedPlace = cachedLocation(item.id);
    if (cachedPlace) {
      setPreciseLocation(cachedPlace);
    } else {
      // Set initial fallback derived from ID
      setPreciseLocation(getInitialLocation());

      // Fetch precise location via AI if not already fetched this session
      if (!hasLocationFetchedRef.current.has(item.id)) {
        hasLocationFetchedRef.current.add(item.id);
        fetchPreciseLocation();
      }
    }
  }, [item]);

  useEffect(() => {
    if (activeTab === 'wikipedia' && !wikiContent) {
      fetchWikipediaArticle();
    }
  }, [activeTab, item.title]);

  const fetchWikipediaArticle = async () => {
    setIsLoadingWiki(true);
    
    // Helper: search Wikipedia and return { title, extract } or null
    const wikiSearch = async (query: string): Promise<{ title: string; extract: string } | null> => {
      try {
        // No `exintro`: the briefing above is already the article's opening
        // paragraph, so an intro-only extract made the two tabs show the same
        // words. The whole article is what a second tab is for.
        const url = `https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrlimit=1&prop=extracts&explaintext=1&exlimit=1&format=json&origin=*`;
        const res = await fetch(url);
        const data = await res.json();
        const pages = data.query?.pages;
        if (!pages) return null;
        const pageId = Object.keys(pages)[0];
        const page = pages[pageId];
        if (pageId === '-1' || !page.extract) return null;
        return { title: page.title, extract: page.extract };
      } catch { return null; }
    };

    try {
      // Build a cascade of progressively broader search terms (all free Wikipedia API)
      const cleanTitle = item.title.replace(/\s*\(.*?\)\s*/g, '').trim();
      const regionParts = item.region.split(',').map((s: string) => s.trim());
      const country = regionParts[regionParts.length - 1] || '';
      const locality = regionParts[0] || '';

      // Extract meaningful keywords from description (skip short/common words)
      const stopWords = new Set(['a','an','the','in','on','at','of','to','and','or','is','are','was','this','that','for','with','by','from','as','it','its','has','be','been','not','but','if','than','so','very','can','will','do','does','did','also','which','these','each']);
      const descWords = (item.description || '').split(/\s+/)
        .map((w: string) => w.replace(/[^a-zA-Z]/g, ''))
        .filter((w: string) => w.length > 4 && !stopWords.has(w.toLowerCase()));
      const uniqueDescWords = [...new Set(descWords)].slice(0, 3);

      const searchQueries = [
        item.title,                                          // 1. Exact title
        cleanTitle,                                          // 2. Cleaned title (no parentheses)
        `${cleanTitle} ${country}`,                          // 3. Title + country
        `${cleanTitle} festival`,                            // 4. Title + festival
        `${cleanTitle} ceremony culture`,                    // 5. Title + culture keywords
        item.region,                                         // 6. Full region
        locality,                                            // 7. Just locality
        country,                                             // 8. Just country
        ...uniqueDescWords.map((w: string) => `${w} ${country}`), // 9. Description keywords + country
      ].filter((q, i, arr) => q && arr.indexOf(q) === i);   // Deduplicate

      let result: { title: string; extract: string } | null = null;

      for (const query of searchQueries) {
        result = await wikiSearch(query);
        if (result) break;
      }

      if (!result) {
        setWikiContent('No relevant Wikipedia article could be found for this event.');
        return;
      }

      // Show a "Related Article" banner if the found article title differs from the event title
      const isExactMatch = result.title.toLowerCase() === item.title.toLowerCase() || result.title.toLowerCase() === cleanTitle.toLowerCase();
      const prefix = !isExactMatch ? `Closest article found: ${result.title}

` : '';
      setWikiContent(prefix + result.extract);
    } catch (e) {
      setWikiContent('Could not load the Wikipedia article.');
    } finally {
      setIsLoadingWiki(false);
    }
  };

  const fetchPreciseLocation = async () => {
    try {
      const locationText = await aiClient.preciseLocation(item.title, item.description);
      if (locationText) {
        setPreciseLocation(locationText);
        storeLocation(item.id, locationText);
      }
    } catch (e) {
      console.error("Location fetch failed", e);
    }
  };

  const handleGenerateAi = async (isAuto = false) => {
    if (!isAuto && isAiGenerated) {
      setDisplayImage(item.imageUrl);
      setIsAiGenerated(false);
      return;
    }

    setIsLoadingAi(true);

    try {
      const dataUrl = await aiClient.eventImage(item.title, item.region, item.description);

      if (dataUrl) {
        storeAiImage(item.id, dataUrl);
        setDisplayImage(dataUrl);
        setIsAiGenerated(true);
      }
    } catch (error) {
      console.error("Failed to generate AI image:", error);
    } finally {
      setIsLoadingAi(false);
    }
  };

  const formatDisplayDate = (start: string, end: string) => {
    const options: Intl.DateTimeFormatOptions = {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    };
    const startDate = new Date(start).toLocaleDateString('en-US', options);
    const endDate = new Date(end).toLocaleDateString('en-US', options);

    if (start === end) {
      return startDate;
    }
    return `${startDate} — ${endDate}`;
  };

  /* ---- Sections ---------------------------------------------------------
     Written once and composed twice. The map column and the reader overlay
     show the same material; only the arrangement differs, so the sections
     are values rather than duplicated markup. */

  const categoryChip = (
    <span
      className="text-[11px] font-bold px-2 py-0.5 rounded uppercase tracking-widest"
      style={{
        color: categoryColor(item.ritualType),
        backgroundColor: `color-mix(in srgb, ${categoryColor(item.ritualType)} 9%, transparent)`,
        border: `1px solid color-mix(in srgb, ${categoryColor(item.ritualType)} 20%, transparent)`,
      }}
    >
      {item.ritualType}
    </span>
  );

  // Goes to the trip, rather than undoing the save. "Saved" answers "where
  // did it go?", and the useful reply is to show the reader. Unsaving stays
  // on the backpack above, which is where they just pressed to save — so the
  // two controls do not compete for the same tap with opposite outcomes.
  const savedBadge = isSaved && onViewSaved ? (
    <button
      type="button"
      onClick={onViewSaved}
      title="See it in your trips"
      className="text-[11px] font-bold text-on-accent bg-accent
                 px-2 min-h-[28px] rounded uppercase tracking-widest
                 inline-flex items-center gap-1 active:opacity-80 transition-opacity"
    >
      <Backpack className="w-3 h-3" />
      Saved
      <ChevronRight className="w-3 h-3" />
    </button>
  ) : null;

  const factsCard = (
    <div className="flex flex-col gap-2.5 bg-raised/40 rounded-xl p-3.5 border border-white/5">
      <div className="flex items-center gap-3">
        <div className="text-accent">
          <Calendar className="w-3.5 h-3.5" />
        </div>
        <span className="text-[12px] text-ink font-medium uppercase tracking-wide">
          {formatDisplayDate(item.startDate, item.endDate)}
        </span>
      </div>

      <div className="h-px bg-white/5 w-full"></div>

      <div className="flex items-center gap-3">
        <div className="text-accent">
          <MapPin className="w-3.5 h-3.5" />
        </div>
        <div className="flex flex-wrap items-baseline gap-2">
          <span className="text-[12px] text-ink font-medium uppercase tracking-wide">
            {preciseLocation || item.region}
          </span>
          <span className="text-[11px] text-ink-faint font-mono">
            {Math.abs(item.coordinates[0]).toFixed(4)}°{item.coordinates[0] >= 0 ? 'N' : 'S'}, {Math.abs(item.coordinates[1]).toFixed(4)}°{item.coordinates[1] >= 0 ? 'E' : 'W'}
          </span>
        </div>
      </div>
    </div>
  );

  const briefingSection = (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <AlignLeft className="w-4 h-4 text-accent" />
        <h4 className="text-[12px] text-ink-dim uppercase font-black tracking-[0.1em]">Briefing</h4>
      </div>
      {briefing ? (
        <div className="k-prose border-l border-line-hard pl-4 space-y-2">
          <p className="text-sm text-ink leading-relaxed font-light">
            {briefing.summary}
          </p>
          {/* CC BY-SA requires attribution, and the reader deserves to know
              this is an encyclopedia summary rather than something the app
              worked out. */}
          <a
            href={briefing.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-[12px] text-ink-faint hover:text-accent transition-colors"
          >
            Wikipedia · {briefing.sourceTitle}
          </a>
        </div>
      ) : curatedNote ? (
        <p className="k-prose text-sm text-ink leading-relaxed font-light border-l border-line-hard pl-4">
          {curatedNote}
        </p>
      ) : (
        // Better to admit the gap than to print "A spectacular natural
        // phenomenon in <place>" back at someone who is reading it directly
        // below the place.
        <p className="text-sm text-ink-dim leading-relaxed font-light border-l border-line-hard pl-4">
          No sourced description yet for this event.
        </p>
      )}
    </div>
  );

  // The way out of the narrow column, offered where the narrowness is felt.
  // The icon in the header corner is findable once you know it exists; this
  // sits directly under the paragraph that was tiring to read.
  //
  // Withheld unless the width would actually change something: a one-line
  // briefing with no photographs takes two lines at 380px and offering a
  // second screen for it is noise. The header control stays either way.
  const readingLength = (briefing?.summary ?? curatedNote ?? '').length;
  const readerCta = (readingLength > 400 || gallery.length > 0) ? (
    <button
      type="button"
      onClick={() => setIsReader(true)}
      className="hidden sm:flex w-full items-center gap-3 px-4 py-3 rounded-xl text-left
                 bg-raised/40 border border-white/5 group
                 hover:bg-raised hover:border-accent/30 transition-colors"
    >
      <Maximize2 className="w-4 h-4 text-accent shrink-0" />
      <span className="flex-1 min-w-0">
        <span className="block text-[12px] font-bold text-ink uppercase tracking-wide">
          Read full screen
        </span>
        <span className="block text-[11px] text-ink-faint">
          {gallery.length > 0
            ? 'A wider column, and the photographs at size'
            : 'A wider column, and room to read'}
        </span>
      </span>
      <ChevronRight className="w-4 h-4 text-ink-faint group-hover:text-accent transition-colors shrink-0" />
    </button>
  ) : null;

  // More photographs, when the resolver found more than one. A single frame
  // proves the event exists; several show what it is, which for this
  // catalogue is most of the reason to go.
  const gallerySection = gallery.length > 0 ? (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Images className="w-4 h-4 text-accent" />
        <h4 className="text-[12px] text-ink-dim uppercase font-black tracking-[0.1em]">
          Photographs
        </h4>
      </div>
      <EventGallery images={gallery} title={item.title} />
    </div>
  ) : null;

  // What it will be like when you are there. Climate normals for this event's
  // own calendar window, not today's weather — the full-analysis screen used
  // to show current conditions at the site, which for an event eight months
  // away told the reader nothing they could use.
  const conditionsSection = (climate || daylight) ? (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Sun className="w-4 h-4 text-accent" />
        <h4 className="text-[12px] text-ink-dim uppercase font-black tracking-[0.1em]">
          Conditions
        </h4>
      </div>
      <ConditionsPanel climate={climate} daylight={daylight} />
    </div>
  ) : null;

  // Getting there. Placed directly under the briefing, because "how would I
  // even reach this" is the next thought after "what is it", and long before
  // any book recommendation.
  const gettingThereSection = (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Plane className="w-4 h-4 text-accent" />
        <h4 className="text-[12px] text-ink-dim uppercase font-black tracking-[0.1em]">
          Getting there
        </h4>
      </div>
      <GettingTherePanel item={item} userCoords={userCoords} />
    </div>
  );

  const insightsSection = item.insights ? (
    <div className="space-y-3 bg-raised/30 p-5 rounded-2xl border border-white/5">
      <div className="flex items-center gap-2 mb-1">
        <Sparkles className="w-3.5 h-3.5 text-accent" />
        <h4 className="text-[12px] text-accent uppercase font-black tracking-[0.1em]">Cultural Intelligence</h4>
      </div>
      <p className="k-prose text-sm text-ink-dim leading-relaxed font-light italic">
        "{item.insights}"
      </p>
    </div>
  ) : null;

  const booksSection = item.recommendedBooks && item.recommendedBooks.length > 0 ? (
    <div className="space-y-5">
      <h4 className="text-[12px] text-ink-faint uppercase font-black tracking-[0.12em] flex items-center gap-2">
        Related Scholarship
      </h4>

      <div className="space-y-3">
        {item.recommendedBooks.map((book, idx) => (
          <a
            key={idx}
            // bookshopLink first: it is the field every book in the catalogue
            // actually has. This read `book.url`, which almost none of them
            // carry, so the whole reading list rendered as links to nowhere.
            href={book.bookshopLink || book.url || book.amazonLink}
            target="_blank"
            rel="noopener noreferrer"
            className="block group bg-raised border border-line rounded-xl p-4 transition-all hover:border-accent/30 hover:bg-raised"
          >
            <div className="flex justify-between items-start mb-2">
              <h5 className="text-[12px] font-bold text-ink group-hover:text-ink transition-colors pr-4 leading-tight">
                {book.title}
              </h5>
              <ShoppingBag className="w-3.5 h-3.5 text-ink-faint group-hover:text-accent flex-shrink-0 transition-colors" />
            </div>
            <div className="flex items-center justify-between">
              <span className="text-[12px] text-ink-faint group-hover:text-ink-dim transition-colors uppercase tracking-widest font-medium">
                BY {book.author}
              </span>
            </div>
          </a>
        ))}
      </div>
    </div>
  ) : null;

  // The extract arrives as plain text (`explaintext=1`), and was being set as
  // innerHTML — so the blank lines between paragraphs collapsed and the whole
  // article rendered as one unbroken 14px run. Rebuilding it into real
  // elements restores the structure, lets the stylesheet reach it, and stops
  // us injecting remote text as markup for no reason.
  //
  // TextExtracts marks section titles as `== Title ==`. The apparatus at the
  // end of an article — references, external links — survives as bare
  // headings once the extract strips their lists, so those go, along with any
  // other section left with nothing under it.
  const WIKI_APPARATUS =
    /^(see also|references|notes|citations|sources|bibliography|external links|further reading)$/i;

  const wikiBlocks = (() => {
    const blocks = (wikiContent ?? '')
      .split(/\n+/)
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => {
        const heading = line.match(/^=+\s*(.+?)\s*=+$/);
        return heading
          ? { kind: 'h' as const, text: heading[1] }
          : { kind: 'p' as const, text: line };
      })
      .filter(block => !(block.kind === 'h' && WIKI_APPARATUS.test(block.text)));
    return blocks.filter((block, i) => block.kind === 'p' || blocks[i + 1]?.kind === 'p');
  })();

  const wikipediaBody = (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="flex items-center gap-2 mb-4">
        <BookOpen className="w-5 h-5 text-accent" />
        <h2 className="text-xl font-black text-ink uppercase tracking-widest">Wikipedia</h2>
      </div>

      {isLoadingWiki ? (
        <div className="flex flex-col items-center justify-center py-12 gap-4">
          <Loader2 className="w-8 h-8 animate-spin text-accent" />
          <span className="text-xs text-ink-faint font-mono uppercase tracking-widest">Loading Article...</span>
        </div>
      ) : wikiBlocks.length > 0 ? (
        <div className="wiki-content">
          {wikiBlocks.map((block, i) => block.kind === 'h'
            ? <h3 key={i}>{block.text}</h3>
            : <p key={i}>{block.text}</p>)}
        </div>
      ) : (
        <p className="text-sm text-ink-dim leading-relaxed font-light">
          No article loaded for this event.
        </p>
      )}
    </div>
  );

  const panelStyles = (
    <style>{`
      .custom-scrollbar::-webkit-scrollbar { width: 4px; height: 2px; }
      .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
      .custom-scrollbar::-webkit-scrollbar-thumb { background: #333; border-radius: 4px; }
      .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #555; }

      .wiki-content p { font-size: 0.875rem; line-height: 1.6; color: var(--k-ink-dim); margin-bottom: 1rem; }
      .wiki-content p:last-child { margin-bottom: 0; }
      .wiki-content h3 {
        font-size: 0.75rem; font-weight: 800; text-transform: uppercase;
        letter-spacing: 0.1em; color: var(--k-ink); margin: 2rem 0 0.75rem;
      }
      .wiki-content h3:first-child { margin-top: 0; }

      @keyframes slideUpFade {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
      }
      .stagger-item {
        opacity: 0;
        animation: slideUpFade 0.5s ease-out forwards;
      }

      /* Reader. The one thing a 380px column cannot give prose is a measure,
         so the overlay sets one — roughly 68 characters, with a line height
         to match. Nothing else about the sections changes. */
      .k-reader .k-prose { max-width: 68ch; }
      .k-reader .k-prose p { font-size: 1.0625rem; line-height: 1.85; letter-spacing: 0.005em; }
      .k-reader .wiki-content { max-width: 68ch; }
      .k-reader .wiki-content p { font-size: 1.0625rem; line-height: 1.85; }
      .k-reader .wiki-content h3 { font-size: 0.8125rem; margin-top: 2.75rem; }

      /* In the column the gallery has to be a scrolling strip of thumbnails.
         With the whole window it can be what it should be: a contact sheet. */
      .k-reader .k-gallery-strip {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 0.6rem;
        overflow: visible;
        max-width: 68ch;
      }
      .k-reader .k-gallery-strip > button { width: auto; height: 150px; }

      /* Opacity only. A transform here — even a settled scale(1) held by
         animation-fill-mode — makes this element the containing block for
         every fixed-position descendant, which is not a thing a fade should
         decide. */
      @keyframes readerIn {
        from { opacity: 0; }
        to { opacity: 1; }
      }
      .k-reader { animation: readerIn 0.28s cubic-bezier(0.16, 1, 0.3, 1) both; }
    `}</style>
  );

  /* ---- Reader ------------------------------------------------------------
     A portal, not a nested overlay: the sidebar that owns this panel sets
     overflow-hidden and a backdrop filter, either of which can clip a fixed
     child. Rendered instead of the column rather than on top of it, so the
     briefing, the climate lookup and the airport data are not fetched twice —
     and because this is the same component instance, none of it reloads when
     the reader opens or closes. */

  if (isReader) {
    return createPortal(
      <div className="k-reader fixed inset-0 z-[90] bg-base overflow-y-auto custom-scrollbar text-ink">
        {/* Controls ride above the hero, where the image is darkest. */}
        <div className="fixed top-5 right-6 z-20 flex gap-2">
          {onToggleSave && (
            <button
              onClick={onToggleSave}
              className={`p-2 rounded-full backdrop-blur-md transition-all border shadow-lg ${isSaved
                ? 'bg-accent border-accent text-on-accent'
                : 'bg-black/60 border-white/10 text-ink hover:bg-accent hover:border-accent hover:text-on-accent'}`}
              title={isSaved ? 'Remove from Itinerary' : 'Add to Itinerary'}
            >
              <Backpack className="w-5 h-5" />
            </button>
          )}
          <button
            onClick={exitReader}
            className="p-2 bg-black/60 hover:bg-accent rounded-full transition-all border border-white/10 shadow-lg text-ink hover:text-on-accent"
            title={variant === 'reader' ? 'Close (Esc)' : 'Back to the map (Esc)'}
          >
            <Minimize2 className="w-5 h-5" />
          </button>
        </div>

        {/* Hero. Full-bleed, with the title on the same left edge the article
            below starts from, so the eye does not have to travel to find it. */}
        <div className="relative h-[46vh] min-h-[280px] w-full overflow-hidden">
          {displayImage ? (
            <img src={displayImage} className="w-full h-full object-cover" alt={item.title} />
          ) : (
            <div className="w-full h-full bg-raised" />
          )}
          <div className="absolute inset-0 bg-gradient-to-t from-base via-base/50 to-black/30 pointer-events-none" />
          <div className="absolute inset-x-0 bottom-0">
            <div className="mx-auto max-w-[1160px] px-8 xl:px-12 pb-10 space-y-4">
              <div className="flex items-center gap-2">
                {categoryChip}
                {savedBadge}
              </div>
              <h1 className="text-4xl xl:text-5xl font-black leading-[1.05] tracking-tight uppercase font-sans max-w-[20ch]">
                {item.title}
              </h1>
              <p className="text-[13px] text-ink-dim uppercase tracking-[0.14em] font-medium">
                {preciseLocation || item.region} · {formatDisplayDate(item.startDate, item.endDate)}
              </p>
            </div>
          </div>
        </div>

        {/* Body. Prose on the left at a readable measure; the things you act
            on — dates, weather, flights — in a rail that stays with you as you
            read, instead of waiting at the bottom of a long scroll. */}
        <div className="mx-auto max-w-[1160px] px-8 xl:px-12 pt-10 pb-28
                        grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_320px] gap-x-14 gap-y-12 items-start">
          <div className="min-w-0 space-y-12">
            <div className="flex gap-1 p-1 bg-raised/40 rounded-xl w-fit border border-white/5">
              {(['summary', 'wikipedia'] as const).map(tab => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-4 py-2 rounded-lg text-[11px] font-black uppercase tracking-widest transition-colors ${activeTab === tab ? 'bg-accent text-on-accent' : 'text-ink-faint hover:text-ink'}`}
                >
                  {tab === 'summary' ? 'Briefing' : 'Wikipedia'}
                </button>
              ))}
            </div>

            {activeTab === 'summary' ? (
              <>
                {briefingSection}
                {gallerySection}
                {insightsSection}
                {booksSection}
              </>
            ) : wikipediaBody}
          </div>

          <aside className="lg:sticky lg:top-8 space-y-8 min-w-0">
            {factsCard}
            {conditionsSection}
            {gettingThereSection}
          </aside>
        </div>

        {panelStyles}
      </div>,
      document.body
    );
  }

  return (
    <div
      className="h-full relative text-ink overflow-y-auto custom-scrollbar flex flex-col"
      {...swipeBack}
    >
      {/* Header Image */}
      <div
        className="h-[260px] w-full relative overflow-hidden flex-shrink-0 group stagger-item"
        style={{ animationDelay: '0s' }}
      >
        <div className="absolute inset-0 bg-raised animate-pulse flex items-center justify-center" style={{ display: isLoadingAi ? 'flex' : 'none' }}>
          <div className="text-[12px] text-ink-faint font-mono uppercase tracking-widest flex flex-col items-center gap-2">
            <Loader2 className="w-5 h-5 animate-spin text-accent" />
            <span>Reconstructing Scene...</span>
          </div>
        </div>
        <img
          src={displayImage}
          className={`w-full h-full object-cover transition-all duration-700 ${isLoadingAi ? 'opacity-0' : 'opacity-100'} ${isAiGenerated ? 'brightness-100' : 'brightness-100 group-hover:scale-105'}`}
          alt={item.title}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-base via-transparent to-black/40 pointer-events-none"></div>

        {/* Top Controls, in the corner, which is only a corner because the
            panel now begins below the map's floating navigation. It used to
            start underneath it: the close button on an open event could not
            be clicked at all on desktop, only the tab sitting over it. */}
        <div className="absolute top-4 right-4 flex gap-2 z-20">
          {/* Reading a long briefing in a 380px column is the complaint this
              answers. Hidden on phones, where the panel is already the whole
              screen and there is nothing to expand into. */}
          <button
            onClick={() => setIsReader(true)}
            className="hidden sm:block p-1.5 bg-black/60 hover:bg-accent rounded-full transition-all border border-white/10 shadow-lg text-ink hover:text-on-accent"
            title="Read full screen"
          >
            <Maximize2 className="w-5 h-5" />
          </button>
          {onToggleSave && (
            <button
              onClick={onToggleSave}
              className={`p-1.5 rounded-full backdrop-blur-md transition-all border shadow-lg ${isSaved
                  ? 'bg-accent border-accent text-on-accent'
                  : 'bg-black/60 border-white/10 text-ink hover:bg-accent hover:border-accent hover:text-on-accent'
                }`}
              title={isSaved ? "Remove from Itinerary" : "Add to Itinerary"}
            >
              <Backpack className="w-5 h-5" />
            </button>
          )}
          <button
            onClick={onClose}
            className="p-1.5 bg-black/60 hover:bg-accent rounded-full transition-all border border-white/10 shadow-lg text-ink hover:text-on-accent"
            title="Close Panel"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 p-6 pb-20 space-y-8 relative z-10 bg-panel/95">
        {activeTab === 'summary' ? (
          <>
            {/* Title Block */}
            <div className="space-y-4 stagger-item" style={{ animationDelay: '0.05s' }}>
              <div className="flex items-center gap-2">
                {categoryChip}
                {savedBadge}
              </div>
              <h2 className="text-3xl font-black text-ink leading-[1.1] tracking-tight uppercase font-sans">
                {item.title}
              </h2>
            </div>

            {/* Essential Info compact */}
            <div className="stagger-item" style={{ animationDelay: '0.1s' }}>
              {factsCard}
            </div>

            {/* "Open Full Analysis" used to be here.
                It led to a second screen that mostly repeated this one — the
                same Wikipedia summary, the same books — plus three things
                that should not have shipped: today's weather at the site,
                which is meaningless for an event eight months out; a video
                search routed through a third-party YouTube proxy; and a tour
                search already offered from the trip planner. The one part
                worth keeping, the climate normals, is now below. */}

            {/* Information Sections */}
            <div className="space-y-8 pt-2 stagger-item" style={{ animationDelay: '0.2s' }}>
              {briefingSection}
              {readerCta}
              {gallerySection}
              {conditionsSection}
              {gettingThereSection}
              {insightsSection}
            </div>

            {booksSection && (
              <div className="pt-8 border-t border-line stagger-item" style={{ animationDelay: '0.25s' }}>
                {booksSection}
              </div>
            )}
          </>
        ) : wikipediaBody}
      </div>

      {/* Footer Tabs */}
      <div className="flex border-t border-white/5 bg-base/50 stagger-item" style={{ animationDelay: '0.3s' }}>
        <button
          onClick={() => setActiveTab('summary')}
          className={`flex-1 py-4 text-center text-[12px] font-black uppercase tracking-widest transition-colors ${activeTab === 'summary' ? 'text-accent bg-white/5' : 'text-ink-faint hover:text-ink hover:bg-white/5'}`}
        >
          Summary
        </button>
        <div className="w-px bg-white/5"></div>
        <button
          onClick={() => setActiveTab('wikipedia')}
          className={`flex-1 py-4 text-center text-[12px] font-black uppercase tracking-widest transition-colors ${activeTab === 'wikipedia' ? 'text-accent bg-white/5' : 'text-ink-faint hover:text-ink hover:bg-white/5'}`}
        >
          Wikipedia
        </button>
      </div>

      {panelStyles}
    </div>
  );
};

export default DetailPanel;
