
import React, { useState, useEffect, useRef } from 'react';
import { CultureItem } from '../types';
import { X, MapPin, BookOpen, ShoppingBag, Sparkles, Loader2, Calendar, AlignLeft, Backpack } from 'lucide-react';
import { aiClient } from "../utils/aiClient";
import { categoryColor } from '../utils/categoryTheme';
import { cachedLocation, storeAiImage, storeLocation } from '../utils/aiImageCache';
import {
  EventBriefing,
  loadEventBriefings,
  meaningfulDescription
} from '../utils/eventBriefings';

interface DetailPanelProps {
  item: CultureItem;
  onClose: () => void;
  onViewInsights: (item: CultureItem) => void;
  isSaved?: boolean;
  onToggleSave?: () => void;
}


const DetailPanel: React.FC<DetailPanelProps> = ({ item, onClose, onViewInsights, isSaved = false, onToggleSave }) => {
  const [displayImage, setDisplayImage] = useState(item.imageUrl);
  const [isAiGenerated, setIsAiGenerated] = useState(false);
  const [isLoadingAi, setIsLoadingAi] = useState(false);
  const [preciseLocation, setPreciseLocation] = useState<string>('');
  const [activeTab, setActiveTab] = useState<'summary' | 'wikipedia'>('summary');
  const [wikiContent, setWikiContent] = useState<string | null>(null);
  const [isLoadingWiki, setIsLoadingWiki] = useState(false);
  const [briefing, setBriefing] = useState<EventBriefing | null>(null);

  // Sourced description, resolved once at build time rather than searched on
  // every open. Falls back to the catalogue line only when that line says
  // something the title and region do not already.
  useEffect(() => {
    let live = true;
    loadEventBriefings().then(all => {
      if (live) setBriefing(all[item.id] ?? null);
    });
    return () => { live = false; };
  }, [item.id]);

  const curatedNote = meaningfulDescription(item);

  // Track if we have already tried auto-generation for this item to prevent loops
  const hasAutoGeneratedRef = useRef<Set<string>>(new Set());
  const hasLocationFetchedRef = useRef<Set<string>>(new Set());

  // Helper to guess country from ID as an immediate fallback
  const getInitialLocation = () => {
    if (!item.id) return item.region;
    const code = item.id.split('-')[0];
    const map: Record<string, string> = {
      'nz': 'New Zealand',
      'uk': 'United Kingdom',
      'usa': 'United States',
      'png': 'Papua New Guinea',
      'cr': 'Costa Rica',
      'aus': 'Australia',
      'dr': 'Dominican Republic',
      'swiss': 'Switzerland'
    };
    const country = map[code] || code.charAt(0).toUpperCase() + code.slice(1);
    return `${country}`;
  };

  useEffect(() => {
    // Reset states when item changes
    setActiveTab('summary');
    setWikiContent(null);
    setIsLoadingWiki(false);

    // --- IMAGE LOGIC ---
    setDisplayImage(item.imageUrl);
    setIsAiGenerated(false);
    setIsLoadingAi(false);

    // --- LOCATION LOGIC ---
    const cachedPlace = cachedLocation(item.id);
    if (cachedPlace) {
      setPreciseLocation(cachedPlace);
    } else {
      // Set initial fallback derived from ID
      setPreciseLocation(getInitialLocation());

      // Fetch precise location via AI if not already fetched this session
      if (!hasLocationFetchedRef.current.has(item.id)) {
        hasLocationFetchedRef.current.add(item.id);
        fetchPreciseLocation();
      }
    }
  }, [item]);

  useEffect(() => {
    if (activeTab === 'wikipedia' && !wikiContent) {
      fetchWikipediaArticle();
    }
  }, [activeTab, item.title]);

  const fetchWikipediaArticle = async () => {
    setIsLoadingWiki(true);
    
    // Helper: search Wikipedia and return { title, extract } or null
    const wikiSearch = async (query: string): Promise<{ title: string; extract: string } | null> => {
      try {
        const url = `https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrlimit=1&prop=extracts&exintro=1&explaintext=1&format=json&origin=*`;
        const res = await fetch(url);
        const data = await res.json();
        const pages = data.query?.pages;
        if (!pages) return null;
        const pageId = Object.keys(pages)[0];
        const page = pages[pageId];
        if (pageId === '-1' || !page.extract) return null;
        return { title: page.title, extract: page.extract };
      } catch { return null; }
    };

    try {
      // Build a cascade of progressively broader search terms (all free Wikipedia API)
      const cleanTitle = item.title.replace(/\s*\(.*?\)\s*/g, '').trim();
      const regionParts = item.region.split(',').map((s: string) => s.trim());
      const country = regionParts[regionParts.length - 1] || '';
      const locality = regionParts[0] || '';

      // Extract meaningful keywords from description (skip short/common words)
      const stopWords = new Set(['a','an','the','in','on','at','of','to','and','or','is','are','was','this','that','for','with','by','from','as','it','its','has','be','been','not','but','if','than','so','very','can','will','do','does','did','also','which','these','each']);
      const descWords = (item.description || '').split(/\s+/)
        .map((w: string) => w.replace(/[^a-zA-Z]/g, ''))
        .filter((w: string) => w.length > 4 && !stopWords.has(w.toLowerCase()));
      const uniqueDescWords = [...new Set(descWords)].slice(0, 3);

      const searchQueries = [
        item.title,                                          // 1. Exact title
        cleanTitle,                                          // 2. Cleaned title (no parentheses)
        `${cleanTitle} ${country}`,                          // 3. Title + country
        `${cleanTitle} festival`,                            // 4. Title + festival
        `${cleanTitle} ceremony culture`,                    // 5. Title + culture keywords
        item.region,                                         // 6. Full region
        locality,                                            // 7. Just locality
        country,                                             // 8. Just country
        ...uniqueDescWords.map((w: string) => `${w} ${country}`), // 9. Description keywords + country
      ].filter((q, i, arr) => q && arr.indexOf(q) === i);   // Deduplicate

      let result: { title: string; extract: string } | null = null;

      for (const query of searchQueries) {
        result = await wikiSearch(query);
        if (result) break;
      }

      if (!result) {
        setWikiContent('No relevant Wikipedia article could be found for this event.');
        return;
      }

      // Show a "Related Article" banner if the found article title differs from the event title
      const isExactMatch = result.title.toLowerCase() === item.title.toLowerCase() || result.title.toLowerCase() === cleanTitle.toLowerCase();
      const prefix = !isExactMatch ? `Closest article found: ${result.title}

` : '';
      setWikiContent(prefix + result.extract);
    } catch (e) {
      setWikiContent('Could not load the Wikipedia article.');
    } finally {
      setIsLoadingWiki(false);
    }
  };

  const fetchPreciseLocation = async () => {
    try {
      const locationText = await aiClient.preciseLocation(item.title, item.description);
      if (locationText) {
        setPreciseLocation(locationText);
        storeLocation(item.id, locationText);
      }
    } catch (e) {
      console.error("Location fetch failed", e);
    }
  };

  const handleGenerateAi = async (isAuto = false) => {
    if (!isAuto && isAiGenerated) {
      setDisplayImage(item.imageUrl);
      setIsAiGenerated(false);
      return;
    }

    setIsLoadingAi(true);

    try {
      const dataUrl = await aiClient.eventImage(item.title, item.region, item.description);

      if (dataUrl) {
        storeAiImage(item.id, dataUrl);
        setDisplayImage(dataUrl);
        setIsAiGenerated(true);
      }
    } catch (error) {
      console.error("Failed to generate AI image:", error);
    } finally {
      setIsLoadingAi(false);
    }
  };

  const formatDisplayDate = (start: string, end: string) => {
    const options: Intl.DateTimeFormatOptions = {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    };
    const startDate = new Date(start).toLocaleDateString('en-US', options);
    const endDate = new Date(end).toLocaleDateString('en-US', options);

    if (start === end) {
      return startDate;
    }
    return `${startDate} — ${endDate}`;
  };

  return (
    <div className="h-full relative text-ink overflow-y-auto custom-scrollbar flex flex-col">
      {/* Header Image */}
      <div
        className="h-[260px] w-full relative overflow-hidden flex-shrink-0 group stagger-item"
        style={{ animationDelay: '0s' }}
      >
        <div className="absolute inset-0 bg-raised animate-pulse flex items-center justify-center" style={{ display: isLoadingAi ? 'flex' : 'none' }}>
          <div className="text-[12px] text-ink-faint font-mono uppercase tracking-widest flex flex-col items-center gap-2">
            <Loader2 className="w-5 h-5 animate-spin text-accent" />
            <span>Reconstructing Scene...</span>
          </div>
        </div>
        <img
          src={displayImage}
          className={`w-full h-full object-cover transition-all duration-700 ${isLoadingAi ? 'opacity-0' : 'opacity-100'} ${isAiGenerated ? 'brightness-100' : 'brightness-100 group-hover:scale-105'}`}
          alt={item.title}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-base via-transparent to-black/40 pointer-events-none"></div>

        {/* Top Controls */}
        <div className="absolute top-4 right-4 flex gap-2 z-20">
          {onToggleSave && (
            <button
              onClick={onToggleSave}
              className={`p-1.5 rounded-full backdrop-blur-md transition-all border shadow-lg ${isSaved
                  ? 'bg-accent border-accent text-on-accent'
                  : 'bg-black/60 border-white/10 text-ink hover:bg-accent hover:border-accent hover:text-on-accent'
                }`}
              title={isSaved ? "Remove from Itinerary" : "Add to Itinerary"}
            >
              <Backpack className="w-5 h-5" />
            </button>
          )}
          <button
            onClick={onClose}
            className="p-1.5 bg-black/60 hover:bg-accent rounded-full transition-all border border-white/10 shadow-lg text-ink hover:text-on-accent"
            title="Close Panel"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 p-6 pb-20 space-y-8 relative z-10 bg-panel/95">
        {activeTab === 'summary' ? (
          <>
            {/* Title Block */}
            <div className="space-y-4 stagger-item" style={{ animationDelay: '0.05s' }}>
              <div className="flex items-center gap-2">
                <span
                  className="text-[11px] font-bold px-2 py-0.5 rounded uppercase tracking-widest"
                  style={{
                    color: categoryColor(item.ritualType),
                    backgroundColor: `color-mix(in srgb, ${categoryColor(item.ritualType)} 9%, transparent)`,
                    border: `1px solid color-mix(in srgb, ${categoryColor(item.ritualType)} 20%, transparent)`,
                  }}
                >
                  {item.ritualType}
                </span>
                {isSaved && (
                  <span className="text-[11px] font-bold text-on-accent bg-accent px-2 py-0.5 rounded uppercase tracking-widest flex items-center gap-1">
                    <Backpack className="w-3 h-3" /> Saved
                  </span>
                )}
              </div>
              <h2 className="text-3xl font-black text-ink leading-[1.1] tracking-tight uppercase font-sans">
                {item.title}
              </h2>
            </div>

            {/* Essential Info compact */}
            <div className="flex flex-col gap-2.5 bg-raised/40 rounded-xl p-3.5 border border-white/5 stagger-item" style={{ animationDelay: '0.1s' }}>
              {/* Date */}
              <div className="flex items-center gap-3">
                <div className="text-accent">
                  <Calendar className="w-3.5 h-3.5" />
                </div>
                <span className="text-[12px] text-ink font-medium uppercase tracking-wide">
                  {formatDisplayDate(item.startDate, item.endDate)}
                </span>
              </div>

              <div className="h-px bg-white/5 w-full"></div>

              {/* Location */}
              <div className="flex items-center gap-3">
                <div className="text-accent">
                  <MapPin className="w-3.5 h-3.5" />
                </div>
                <div className="flex flex-wrap items-baseline gap-2">
                  <span className="text-[12px] text-ink font-medium uppercase tracking-wide">
                    {preciseLocation || item.region}
                  </span>
                  <span className="text-[11px] text-ink-faint font-mono">
                    {Math.abs(item.coordinates[0]).toFixed(4)}°{item.coordinates[0] >= 0 ? 'N' : 'S'}, {Math.abs(item.coordinates[1]).toFixed(4)}°{item.coordinates[1] >= 0 ? 'E' : 'W'}
                  </span>
                </div>
              </div>
            </div>

            {/* Main Actions */}
            <div className="stagger-item" style={{ animationDelay: '0.15s' }}>
              <button
                onClick={() => onViewInsights(item)}
                className="w-full bg-raised hover:bg-accent hover:text-on-accent text-ink border border-line-hard hover:border-accent font-bold py-3.5 rounded-xl text-[12px] uppercase tracking-[0.1em] transition-all flex items-center justify-center gap-3 shadow-lg hover:shadow-[0_0_20px_var(--k-glow)]"
              >
                <Sparkles className="w-4 h-4" />
                <span>Open Full Analysis</span>
              </button>
            </div>

            {/* Information Sections */}
            <div className="space-y-8 pt-2 stagger-item" style={{ animationDelay: '0.2s' }}>

              {/* Overview */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <AlignLeft className="w-4 h-4 text-accent" />
                  <h4 className="text-[12px] text-ink-dim uppercase font-black tracking-[0.1em]">Briefing</h4>
                </div>
                {briefing ? (
                  <div className="border-l border-line-hard pl-4 space-y-2">
                    <p className="text-sm text-ink leading-relaxed font-light">
                      {briefing.summary}
                    </p>
                    {/* CC BY-SA requires attribution, and the reader deserves
                        to know this is an encyclopedia summary rather than
                        something the app worked out. */}
                    <a
                      href={briefing.sourceUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-[12px] text-ink-faint hover:text-accent transition-colors"
                    >
                      Wikipedia · {briefing.sourceTitle}
                    </a>
                  </div>
                ) : curatedNote ? (
                  <p className="text-sm text-ink leading-relaxed font-light border-l border-line-hard pl-4">
                    {curatedNote}
                  </p>
                ) : (
                  // Better to admit the gap than to print "A spectacular
                  // natural phenomenon in <place>" back at someone who is
                  // reading it directly below the place.
                  <p className="text-sm text-ink-dim leading-relaxed font-light border-l border-line-hard pl-4">
                    No sourced description yet for this event.
                  </p>
                )}
              </div>

              {/* Insights */}
              {item.insights && (
                <div className="space-y-3 bg-raised/30 p-5 rounded-2xl border border-white/5">
                  <div className="flex items-center gap-2 mb-1">
                    <Sparkles className="w-3.5 h-3.5 text-accent" />
                    <h4 className="text-[12px] text-accent uppercase font-black tracking-[0.1em]">Cultural Intelligence</h4>
                  </div>
                  <p className="text-sm text-ink-dim leading-relaxed font-light italic">
                    "{item.insights}"
                  </p>
                </div>
              )}
            </div>

            {/* BOOK RECOMMENDATIONS SECTION */}
            {item.recommendedBooks && item.recommendedBooks.length > 0 && (
              <div className="space-y-5 pt-8 border-t border-line stagger-item" style={{ animationDelay: '0.25s' }}>
                <div className="flex items-center justify-between">
                  <h4 className="text-[12px] text-ink-faint uppercase font-black tracking-[0.12em] flex items-center gap-2">
                    Related Scholarship
                  </h4>
                </div>

                <div className="space-y-3">
                  {item.recommendedBooks.map((book, idx) => (
                    <a
                      key={idx}
                      href={book.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block group bg-raised border border-line rounded-xl p-4 transition-all hover:border-accent/30 hover:bg-raised"
                    >
                      <div className="flex justify-between items-start mb-2">
                        <h5 className="text-[12px] font-bold text-ink group-hover:text-ink transition-colors pr-4 leading-tight">
                          {book.title}
                        </h5>
                        <ShoppingBag className="w-3.5 h-3.5 text-ink-faint group-hover:text-accent flex-shrink-0 transition-colors" />
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-[12px] text-ink-faint group-hover:text-ink-dim transition-colors uppercase tracking-widest font-medium">
                          BY {book.author}
                        </span>
                      </div>
                    </a>
                  ))}
                </div>
              </div>
            )}
          </>
        ) : (
          <div className="space-y-6 animate-in fade-in duration-300">
            <div className="flex items-center gap-2 mb-4">
              <BookOpen className="w-5 h-5 text-accent" />
              <h2 className="text-xl font-black text-ink uppercase tracking-widest">Wikipedia</h2>
            </div>

            {isLoadingWiki ? (
              <div className="flex flex-col items-center justify-center py-12 gap-4">
                <Loader2 className="w-8 h-8 animate-spin text-accent" />
                <span className="text-xs text-ink-faint font-mono uppercase tracking-widest">Loading Article...</span>
              </div>
            ) : (
              <div
                className="wiki-content"
                dangerouslySetInnerHTML={{ __html: wikiContent || '' }}
              />
            )}
          </div>
        )}
      </div>

      {/* Footer Tabs */}
      <div className="flex border-t border-white/5 bg-base/50 stagger-item" style={{ animationDelay: '0.3s' }}>
        <button
          onClick={() => setActiveTab('summary')}
          className={`flex-1 py-4 text-center text-[12px] font-black uppercase tracking-widest transition-colors ${activeTab === 'summary' ? 'text-accent bg-white/5' : 'text-ink-faint hover:text-ink hover:bg-white/5'}`}
        >
          Summary
        </button>
        <div className="w-px bg-white/5"></div>
        <button
          onClick={() => setActiveTab('wikipedia')}
          className={`flex-1 py-4 text-center text-[12px] font-black uppercase tracking-widest transition-colors ${activeTab === 'wikipedia' ? 'text-accent bg-white/5' : 'text-ink-faint hover:text-ink hover:bg-white/5'}`}
        >
          Wikipedia
        </button>
      </div>

      <style>{`
        .custom-scrollbar::-webkit-scrollbar { width: 4px; height: 2px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #333; border-radius: 4px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #555; }
        
        .wiki-content h2 { font-size: 1.25rem; font-weight: 900; text-transform: uppercase; letter-spacing: 0.1em; color: white; margin-top: 2rem; margin-bottom: 1rem; }
        .wiki-content h3 { font-size: 1.125rem; font-weight: 700; color: #e5e5e5; margin-top: 1.5rem; margin-bottom: 0.75rem; }
        .wiki-content p { font-size: 0.875rem; line-height: 1.6; color: #d4d4d4; margin-bottom: 1rem; }
        .wiki-content ul { list-style-type: disc; padding-left: 1.5rem; margin-bottom: 1rem; color: #d4d4d4; font-size: 0.875rem; }
        .wiki-content li { margin-bottom: 0.25rem; }
        .wiki-content a { color: var(--k-accent); text-decoration: none; }
        .wiki-content a:hover { text-decoration: underline; }
        
        @keyframes slideUpFade {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .stagger-item {
          opacity: 0;
          animation: slideUpFade 0.5s ease-out forwards;
        }
      `}</style>
    </div>
  );
};

export default DetailPanel;
